version: '3'

services:
  database:
    image: mariadb:11
    ports:
      - 3306:3306
    volumes:
      - ./database_data:/var/lib/mysql
    environment:
      MARIADB_USER: mangos
      MARIADB_PASSWORD: mangos
      MARIADB_ROOT_PASSWORD: mangos
    logging:
      options:
        max-size: 10m
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect"]

  realmd:
    image: mangoszero:latest
    build: .
    ports:
      - 3724:3724
    volumes:
      - ./workdir/realmd:/server/install/workdir
    environment:
      LOGIN_DATABASE_INFO: database;3306;root;mangos;realmd
    ulimits:
      # https://github.com/mserajnik/vmangos-deploy/commit/cfff3d5495d51901135d627354865f6b0b419e29
      nofile: 1024
      # Disable core dumps on crashes:
      core: 0
    logging:
      options:
        max-size: 10m
    depends_on:
      database:
        condition: service_healthy

  server:
    tty: true
    stdin_open: true
    image: mangoszero:latest
    build: .
    ports:
      - 8085:8085
      - 3443:3443
    volumes:
      - ./workdir/server:/server/install/workdir
    environment:
      LOGIN_DATABASE_INFO: database;3306;root;mangos;realmd
      WORLD_DATABASE_INFO: database;3306;root;mangos;mangos0
      CHARACTER_DATABASE_INFO: database;3306;root;mangos;character0
    ulimits:
      # https://github.com/mserajnik/vmangos-deploy/commit/cfff3d5495d51901135d627354865f6b0b419e29
      nofile: 1024
      # Disable core dumps on crashes:
      core: 0
    logging:
      options:
        max-size: 10m
    depends_on:
      database:
        condition: service_healthy
