version: '3'

services:
  database:
    image: mariadb:11
    ports:
      - "3306:3306"
    volumes:
      - ./database_data:/var/lib/mysql
    environment:
      MARIADB_USER: mangos
      MARIADB_PASSWORD: mangos
      MARIADB_ROOT_PASSWORD: mangos
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect"]

  realmd:
    image: mangoszero:latest
    build: .
    ports:
      - "3724:3724"
    volumes:
      - ./launch_realmd.sh:/server/install/launch.sh:ro
    environment:
      LOGIN_DATABASE_INFO: database;3306;root;mangos;realmd
    depends_on:
      database:
        condition: service_healthy

  server:
    tty: true
    stdin_open: true
    image: mangoszero:latest
    build: .
    ports:
      - "8085:8085"
    volumes:
      - ./launch_mangosd.sh:/server/install/launch.sh:ro
      - ./gamedata/maps:/server/install/etc/maps:ro
      - ./gamedata/vmaps:/server/install/etc/vmaps:ro
      - ./gamedata/mmaps:/server/install/etc/mmaps:ro
      - ./gamedata/dbc:/server/install/etc/dbc:ro
    environment:
      LOGIN_DATABASE_INFO: database;3306;root;mangos;realmd
      WORLD_DATABASE_INFO: database;3306;root;mangos;mangos0
      CHARACTER_DATABASE_INFO: database;3306;root;mangos;character0
    depends_on:
      database:
        condition: service_healthy
